### ISSUE TITLE
Removing bodies with api.subscribe hook enabled causing errors.

### ISSUE THREAD

**Issue by indiebubbler** [pmndrs/use-cannon#115]
If you use
`  useEffect(() => {api.velocity.subscribe((p) => (currentVel.current = p))})`
on a particular body, there is chance that removing this body from the scene will cause an error and stop physics to work. It's not consistent behavior but it happens each time sooner or later.

Following sandbox adds and removes balls into the scene in 500ms intervals. After 'sometime' it will cause:
```
TypeError
Y[I] is not a function
eval
https://mu1ie.csb.app/node_modules/use-cannon/dist/Provider-f05cb643.js:54:122
Worker.m.onmessage
https://mu1ie.csb.app/node_modules/use-cannon/dist/Provider-f05cb643.js:54:98
```
 
 Sandbox: 
https://codesandbox.io/s/friendly-sinoussi-mu1ie?file=/src/index.js
 
Removing the api.subscribe line solves the problem.

**Comment by jak2030** [comment]
Running into the same issue!

**Comment by andreivips** [comment]
Getting this when component is recreated,
error targets https://github.com/pmndrs/use-cannon/blob/0243fb366f7a1a5343cfb9930fe274f5fee9a6d7/src/worker.js#L111
with `worker.js:111 Uncaught TypeError: Cannot read property 'position' of undefined`
or "TypeError Y[I]"

then here:

https://github.com/pmndrs/use-cannon/blob/0243fb366f7a1a5343cfb9930fe274f5fee9a6d7/src/worker.js#L217

    case 'subscribe': {
      const { id, type } = props
      subscriptions[id] = [uuid, type]
      break
    }
    case 'unsubscribe': {
      delete subscriptions[props] // ?
      break
    }

looks like worker and hooks `subscriptions` gets out of sync

**Comment by indiebubbler** [comment]
I wish I knew how to fix this issue ;)

**Comment by indiebubbler** [comment]
Hi, 
Just heads up to let you all know, that I've updated original sandbox to use latest version of packages (cannon 1.1.1, r3f 6.0.17 etc.) and the error still persists, although it has changed its description slightly. It's the same problem though IMO. 

```
TypeError
subscriptions[id] is not a function
```

https://codesandbox.io/s/friendly-sinoussi-mu1ie?file=/src/index.js

**Comment by David-Beale** [comment]
I've been scratching my head over this all afternoon (I'm trying to use a slider to add/remove objects). 

I've added a PR to fix this:
https://github.com/pmndrs/use-cannon/pull/195
