### ISSUE TITLE
Broken in v5 of react-three-fiber

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/use-cannon#118]
After updating to `react-three-fiber` version 5.0.0, `use-cannon` is giving the following error:

```
TypeError: e is not a function
```
In the following sandbox I just forked the "Simple example" from the README and changed the r3f version to 5.0.0, there you can see the error:
https://codesandbox.io/s/r3f-cannon-instanced-physics-forked-gnk4j

**Comment by drcmda** [comment]
not 100% sure what it is, but if you switch to react17-rc1 it works.

**Comment by drcmda** [comment]
should be fixed in 5.0.1
