### ISSUE TITLE
A scene with a lot of mesh !?

### ISSUE THREAD

**Issue by Franckapik** [pmndrs/use-cannon#120]
Hi !
I would like to know what is the best way to set physics on a scene with a lot of mesh ?
I am using blender and gtlfLoader so i have a lot of mesh and sometimes some groups.
On the scene, there one player (fps) moving with keyboard.
I would like to put mass = 0 on objects to allow collision. But i can't have just one useBox and insert the ref={ref} in each line of code of the converted file. (gltftojsx) 

So do i have to write a lot of useBox or should i merge all "passive object with mass 0" and then use useCompoundBody ?
Or is it possible to have a kind of wrapper or a map to apply physics on each component ?
Is there a script to export all objects in multiples gltf files maybe ? 

A lot of question sorry... Just waiting for some idea before trying all this !
Thank you !!

F.

**Comment by drcmda** [comment]
if the objects are similar i would use instancing. otherwise, each object needs its physics counterpart. that could be abstracted through components for instance

```jsx
const { nodes } = useLoader(...)
return Object.entries(nodes).map(([key, value]) => <Object key={key} .... />

...
function Object(props) {
  const ref = useXyz(...)
  return <mesh ref={ref} ...

**Comment by Franckapik** [comment]
Thank you @drcmda ! 🙂
It was exactly what i was looking for ! 
I will give a try tonight to check if there is no problems with the 2nd option ...

**Comment by Franckapik** [comment]
Here is my code now with physics through components : 

```
export default function All2(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/all.gltf')
  const setVideoPos = useStore(state => state.setVideoPos)

  return (
    Object.entries(nodes).map(
      ([name, obj]) => {
      return <ObjMesh key={name} {...obj} position={obj.getWorldPosition()}  />
    }
  )
  )
}

const ObjMesh = (props) => {

  const v = props.position;

  const [cube, api] = useBox(() => ({
    mass: 0,
    args: [2, 2, 2],
    position: [v.x,v.y,v.z],
  }));

  return (
      <mesh ref={cube} material={props.material} geometry={props.geometry} />
  )
}
```

It's working... I should now separate object with mass : 0 and mass : 1.
Thank you @drcmda 

F.

**Comment by Franckapik** [comment]
Hi,
I have one issue with mesh which have multiples materials.
When i map the nodes object from gtlf loader, it consider each material as a mesh, and appy physics on them. So i see my scene exploding...
Is it possible to apply physics on group only ? and return a mesh without physics for materials ?

I don't know if someone had this situation...

![image](https://user-images.githubusercontent.com/21478769/96440717-a7409d00-1208-11eb-8835-e7fdea5a08d6.png)

thank you a lot !
