### ISSUE TITLE
Feature request - changing gravity dynamically

### ISSUE THREAD

**Issue by lourd** [pmndrs/use-cannon#126]
Dynamically changing the `gravity` prop given to the `Physics` component currently has no effect. This is unexpected, as React components should always respond to new props being passed. There's plenty of creative use cases where you might want to change the physics system's gravity.

**Comment by hazem3500** [comment]
is there a workaround for this?

**Comment by drcmda** [comment]
> is there a workaround for this?

there is, a pull request 😅

**Comment by hazem3500** [comment]
@drcmda hehe 😁, I'll see what I can do
