### ISSUE TITLE
Can a complex geometry (from a gltf file) be used to detect collisions?

### ISSUE THREAD

**Issue by ianmethyst** [pmndrs/use-cannon#127]
I made a model that has a invisible geometry that should act like as a cage for the physics: 

![image](https://user-images.githubusercontent.com/17324893/97358160-9da6dd00-1879-11eb-934e-b079671e28e6.png)

Is there a way to use the highlighted (orange) for this purpose? I'm trying to make something like a walking simulator, and the user shouldn't be able to cross that bound.

I was thinking of splitting it into smaller parts that are all convex, but that sounds pretty time consuming and I'm not even sure if it will work. Maybe I'm missing something and there is an easier way to achieve this?

**Comment by indiebubbler** [comment]
I think you need to useTrimesh, but be aware that it will detect collisions only against spheres.

```
export const TheModel = ({ ...props }) => {
    const { position, rotation } = props
    const { nodes } = useLoader(GLTFLoader, "model.glb");
    const vertices = geometry.attributes.position.array;
    const indices = geometry.index.array
    const [ref] = useTrimesh(() => ({
        rotation,
        position,
        mass: 0,
        args: [vertices, indices]
    }))
    return (
        <mesh ref={ref} geometry={geometry} >
            <meshStandardMaterial attach="material" color='#ff0000' />
        </mesh>
    )
}
```

**Comment by ianmethyst** [comment]
Thanks! I ended up using trimesh in that way

**Comment by Glavin001** [comment]
> [trimesh] will detect collisions only against spheres.

FYI I'm working on a way easily convert complex geometries into decomposed convex shapes in browser/Node.js, such that they can collide with other shapes, not just spheres: https://twitter.com/GlavinW/status/1518397865592303618?s=20&t=db0kTGnYxorVMd-_93CqjQ
Works well with Cannon in my testing.

**Comment by sawsew467** [comment]
> I think you need to useTrimesh, but be aware that it will detect collisions only against spheres.
> 
> ```
> export const TheModel = ({ ...props }) => {
>     const { position, rotation } = props
>     const { nodes } = useLoader(GLTFLoader, "model.glb");
>     const vertices = geometry.attributes.position.array;
>     const indices = geometry.index.array
>     const [ref] = useTrimesh(() => ({
>         rotation,
>         position,
>         mass: 0,
>         args: [vertices, indices]
>     }))
>     return (
>         <mesh ref={ref} geometry={geometry} >
>             <meshStandardMaterial attach="material" color='#ff0000' />
>         </mesh>
>     )
> }
> ```

I don't know what is 'geometry', where you import it to use?
