### ISSUE TITLE
Please provide missing `main` key in package.json

### ISSUE THREAD

**Issue by darwin** [pmndrs/use-cannon#131]
I'm consuming this npm package in a [clojurescript project](https://github.com/binaryage/cljs-react-three-fiber). Currently our [tooling](https://github.com/thheller/shadow-cljs) does not recognise `module` in `package.json`. I had to fork your project and add a missing `main` key to make it work:
https://github.com/darwin/use-cannon/commit/4ea063cfb42f21d25fd0fb42018a7da0d551eca8

Thanks!

**Comment by stockHuman** [comment]
Hey @darwin, using `module` vs `main` suggests ES `import` syntax over commonjs' `require`. You can see in the very first phrase of the output file that what this library builds is ESM all the way down. As such, adding main (presently a recognized property for modules exporting with cjs syntax compatible with Node) would imply something that simply isn't true. _Module_ is non-standard, but so is import syntax.

See [this discussion](https://github.com/nodejs/node/issues/34027) and [this announcement](https://github.com/nodejs/modules/blob/main/doc/new-implementation-announcement.md#es-module-code-in-packages) on the subject. If you have more up-to-date information about this, do share. Good luck with your project!
