### ISSUE TITLE
Please reconsider using dynamic imports

### ISSUE THREAD

**Issue by darwin** [pmndrs/use-cannon#132]
I'm consuming this npm package in a [clojurescript project](https://github.com/binaryage/cljs-react-three-fiber). Currently our [tooling](https://github.com/thheller/shadow-cljs) (which relies on processing the code via google closure compiler) does not support dynamic imports. I had to fork your project and turn it into a static import:
https://github.com/darwin/use-cannon/commit/81fb03fda4aaf31b60085ece9118cb02183fce74

Not sure what was your motivation for dynamic imports usage and how important it is. Eventually I would like ditch my fork and return back to your version. 

For reference here is my discussion with a knowledgeable person developing clojurescript build tooling:

---

17:56 darwin: 
thheller just a follow up, thanks for your insigths, I was able to work around the dynamic import issue by forking the repo and turning it into static import[1], luckily that was the only instance of dynamic import in my npm deps. By looking around I noticed PR[2] in closure compiler, so I guess a support for dynamic imports is imminent upstream
[1] https://github.com/darwin/use-cannon/commit/81fb03fda4aaf31b60085ece9118cb02183fce74
[2] https://github.com/google/closure-compiler/pull/3706

18:00 thheller:
nah not really. it'll most likely just be ignored. https://github.com/google/closure-compiler/issues/3707 (edited) 
I also think it should NOT be supported. it is sort of annoying if libraries do this because they enforce code splitting on you in places where it might not actually make sense for your app.
sure there needs to be a way to do conditional code loading somehow but this is just one of the latest hacks in this area ...

18:03 darwin:
I’d like to open an issue with use-cannon and persuade them not to use dynamic imports so I could eventually return to their official version.
Not sure if I have good arguments though, I’m not familiar with this new JS stuff. (edited) 

18:12 thheller:
well I don't really know why they are doing this so I can't say either
from the looks of it they do it to only conditionally load the Provider stuff when in a context with window
so presumably the code can also be loaded in a worker where they don't want that code
but I don't get why there is import { ProviderProps } from './Provider' and then import('./Provider')
so I don't really understand what this code is even supposed to do from the bundler perspective

18:16 darwin:
I was also wondering about that repeated ./Provider import, once static, second time dynamic, also that was causing warnings about cyclic dependencies when I was trying to compile the dist files of the package on my machine, because provider imports index again. Anyways, thanks for your points, I will ask them in an issue. (edited) 

18:16 thheller: 
I'd expect webpack do duplicate content but no clue why anyone would want that

18:17 thheller:
would be interesting to see what webpack actually does

18:22
thheller hmm looks like the ProviderProps is just a type so probably a misplaced import that should be in the import type further up 
maybe the typescript compiler removes that import later so it never gets to webpack

---

Thanks for your consideration.

**Comment by stockHuman** [comment]
Hello, thanks for proposing this. On a hunch, your fork solved #143, and likely solves #134 as well. I'd like to investigate the decision to lazy load / import dynamically, but in the mean time, a pull request is certainly welcome. 

Thanks again.

**Comment by stockHuman** [comment]
I integrated your branch, released in `v0.5.4`. :)
