### ISSUE TITLE
Error when loaded via mountLazyComponent

### ISSUE THREAD

**Issue by thewizardwand** [pmndrs/use-cannon#134]
I am using typescript and the ionic build environment.
I was able to get Canvas from react three fiber, as well as XRCanvas.
When I added useCannons <Physics> node to the XR Canvas this happened.
It also happened when I rolled back to the <Canvas> node of react three fiber.
I thought perhaps the default ionic web worker was interfering, but after removing it, same error.
Now I suspect this bug is due to the way modules are lazy loaded and chunked in ionic.

![image](https://user-images.githubusercontent.com/241176/99882132-812d6480-2bdb-11eb-8e0f-ea608fe5092b.png)

**Comment by molebox** [comment]
I saw this very same error on a build with NextJs.

**Comment by gregStevenard** [comment]
I've just encountered the exact same issue. Have you been able to resolve it @thewizardwand ?

**Comment by thewizardwand** [comment]
Alas, my solution was to switch back to unreal engine, so I didn't really resolve it... 
I remain open to the react-three-fiber eco-system, I'm hoping to experiment further when this is resolved.

**Comment by stockHuman** [comment]
Hey @thewizardwand, could you try `v0.5.4`? I believe it has the fixes you need.
