### ISSUE TITLE
Updating mass not working

### ISSUE THREAD

**Issue by wiledal** [pmndrs/use-cannon#144]
### Problem
Calling `api.mass.set(x)` after a body is created does nothing.

### Possible solution
Add call to `body.updateMassProperties()` around here: https://github.com/pmndrs/use-cannon/blob/master/src/worker.js#L238

As per documentation: https://schteppe.github.io/cannon.js/docs/classes/Body.html#method_updateMassProperties

**Comment by Franckapik** [comment]
I have changed the setMass function according to @wiledal solution. It's working by setting shape type to 1 (dynamic)
https://github.com/Franckapik/use-cannon/blob/update_mass/src/worker.js#L240

Thank you for your message here !! It help me a lot !

**Comment by stockHuman** [comment]
Should setMass assume that an update to a zero-mass body implies a need for dynamics, and to particularly set it to dynamic (instead of, say, kinematic)?

**Comment by rrelmy** [comment]
@stockHuman Is there a reason the version (v0.5.4) with this fix is not yet published on [npmjs](https://www.npmjs.com/package/use-cannon)?

**Comment by stockHuman** [comment]
Hi @rrelmy. Yes, the package was [renamed in September](https://github.com/pmndrs/use-cannon/pull/117), to match others as a _@react-three_ family. Per the first line in the readme: `yarn add @react-three/cannon` will pull from [npmjs](https://www.npmjs.com/package/@react-three/cannon). In the future, you'll see a deprecation warning when installing `use-cannon`.
