### ISSUE TITLE
This library is an opensource joke ?

### ISSUE THREAD

**Issue by andreivips** [pmndrs/use-cannon#164]
Its not experimental, it has major bugs left to avoid serious usage of this lib, yes ? Why then...

Meanwhile r3f is just great, and this one is show off or something.
https://github.com/pmndrs/use-cannon/issues/115
**next, explore...**

**Comment by stockHuman** [comment]
We welcome your pull request, then.

**Comment by andreivips** [comment]
Its a long root.
