### ISSUE TITLE
Deprecate `use-cannon` NPM package?

### ISSUE THREAD

**Issue by talk2much** [pmndrs/use-cannon#187]
@stephencorwin That's great that you've renamed package `use-cannon` to `@react-three/cannon` in 492ad3d03a0907895430692e9d2638e999c97b0a but I didnt know that. I think its a good practice to update the readme for the old package before publishing package with a new name. Why don't you deprecate the old package then? For example `react-three-fiber` seems to be deprecated and its cool

**Comment by drcmda** [comment]
good point, i deprecated it

**Comment by stephencorwin** [comment]
Thanks for taking care of that. I'll make sure to do this in the future :)
