### ISSUE TITLE
Gatsby.js + @react-three/cannon runtime error

### ISSUE THREAD

**Issue by DevMostafaNassar** [pmndrs/use-cannon#196]
👋 Hi there, for issues that could be related to cannon itself or threejs etc, please consider using github-discussions: https://github.com/react-spring/use-cannon/discussions
![isses](https://user-images.githubusercontent.com/47220002/120119070-f59e1d00-c195-11eb-8daf-447278f991b4.png)
![issue](https://user-images.githubusercontent.com/47220002/120119046-d43d3100-c195-11eb-80ed-664483418527.png)
![issue-](https://user-images.githubusercontent.com/47220002/120119048-dbfcd580-c195-11eb-93c6-2d3316144e2e.png)

**Comment by stockHuman** [comment]
Hello, this is unfortunately too little information to begin solving this issue. Is this related to v1.2.1? Does 1.2.0 work? Would you have a codesandbox to illustrate, or even the project you're working on itself?
