### ISSUE TITLE
Add ability to debug physics bodies with wireframes

### ISSUE THREAD

**Issue by codynova** [pmndrs/use-cannon#21]
I laid the groundwork for the ability to debug most types of physics bodies with wireframes in commit 7f8ce66. This was based on schteppe's [original CannonDebugRenderer](https://github.com/schteppe/cannon.js/blob/master/tools/threejs/CannonDebugRenderer.js) and my [earlier rough pass in TS](https://github.com/codynova/action-game/blob/master/src/debug/useCannonWireframes.ts). I haven't tested this code at all, or seen it working - but my previous TS version works great for all the shapes that I have tested.

@drcmda This code requires references to all of the bodies in the Cannon.World on initialization. It should also be possible to add the option for individual wireframes to each of the shape hooks - although I would want to discuss the api. I'm wondering what is the most ergonomic way to retrieve the bodies from the worker?

**Comment by drcmda** [comment]
The worker communicates the bodies via the sync onmessage, the physics provider keeps them in a record. Check out the examples folder, makes it easier to test.

**Comment by codynova** [comment]
@drcmda I see that `sync` provides the body `uuid`s. How do you feel about adding a way to retrieve the Cannon object references? i.e. `world.bodies`

**Comment by drcmda** [comment]
maybe via useImperativeHandle and Physics, which would allow us to define an api for that component. but wouldnt do much because the bodies are sandboxed, they cant be accessed on the main thread.

**Comment by codynova** [comment]
I'm having trouble coming up with a solution that would allow the wireframes code to be eliminated via tree shaking. The basic idea is to calculate the Three geometry based on the Cannon shape, then draw a wireframe mesh using that geometry and update it each frame.

**Comment by drcmda** [comment]
web-worker have pretty terrible dx, tree shaking is impossible.

make it an extra module perhaps?

```jsx
import { Physics, useBox } from 'use-cannon'
import { wireframe } from 'use-cannon/wireframe'
```

**Comment by codynova** [comment]
An extra module was my thought - but the worker is the only place that collocates all the `world.bodies`. Presumably we would need a second implementation of the worker and Physics component for development. At that point it may not be worth it unless there are other benefits - as great as wireframes are for debugging. Hopefully there is a much simpler solution I'm overlooking.

**Comment by codynova** [comment]
I suppose we could also have a wireframe version of each hook but again that seems unwieldy at best...

**Comment by codynova** [comment]
Sorry for the delayed response. How would you expect that `wireframe` is consumed by the hook or Physics component? Since we can't pass callbacks into the worker, the only option I can think of that would maintain the ability to tree shake is to have a second debug implementation of the worker.

**Comment by codynova** [comment]
Maybe the event bridge could communicate the position and quaternion each frame, but I'm not sure if that would negatively affect performance.

**Comment by drcmda** [comment]
i added a new entry to rollup, it's creating two outputs now:

dist/index.js
dist/debug/index.js

so users can do import {...} from 'use-cannon/debug

that could be a good starting point for added functionality like wireframes etc

**Comment by drcmda** [comment]
hey @codynova any progress on the wireframe? i think i start to understand now why it's so important. i'm struggling hard with positioning objects correctly and figuring out shapes.

**Comment by codynova** [comment]
Yeah, as soon as you start using the more complicated shapes, or adding your own primitives (like Capsule shape), or making compound shapes - you _really_ need the wireframes, and maybe an [AxisHelper](https://threejs.org/docs/#api/en/helpers/AxesHelper)

**Comment by codynova** [comment]
I'll get back to the wireframes now, the bulk of the work is already done, I should be able to ship it today

**Comment by codynova** [comment]
@drcmda I've been trying to figure out how to integrate the wireframe renderer with the worker, but the changes to the bridge would be extensive. We need to communicate a bunch of geometry information for each body, with the compound bodies being composed of many geometries - and the more complex shapes are composed of unique geometries. In addition, setting up the exports in a way that allows tree-shaking (even with the new `dist/debug` directory) would require a lot of refactoring of the core code to prevent needing to maintain duplicates of everything. I think it can work, but it will take time and extensive changes - but I had another thought, might it just be easier to use a non-webworker physics Provider for debugging purposes only?

**Comment by drcmda** [comment]
for dist/debug tree-shaking isn't needed, you can go all in. it's also not minified, so it won't be feasible in production, similar to react dev mode. it might even be possible to do this dynamically later by reading out process.env later on.

**Comment by drcmda** [comment]
there might be a simpler way perhaps, what about sneaking in an imperative boundary box helper, which we scale in the way the args were given? all on the main thread - worker not involved.

**Comment by drcmda** [comment]
tried it out, ...

<img width="500" alt="Screenshot 2020-03-22 at 23 01 39" src="https://user-images.githubusercontent.com/2223602/77261778-51ffd580-6c91-11ea-9f49-57cc9122a479.png">

```jsx
export function useBox(fn: BoxFn, deps: any[] = []) {
  const args = useBody('Box', fn, (args) => args || [0.5, 0.5, 0.5], deps)

  useEffect(() => {
    const object = args[0].current
    if (object) {
      const box = new THREE.Box3()
      box.setFromObject(object)
      box.min.copy(object.worldToLocal(box.min))
      box.max.copy(object.worldToLocal(box.max))
      const helper = new THREE.Box3Helper(box, new THREE.Color("0xffff00"))
      helper.renderOrder = 10000000
      ;(helper.material as any).depthTest = false
      object.add(helper)
      return () => void object.remove(helper)
    }
  }, [])

  return args
}
```

**Comment by codynova** [comment]
I'm not concerned with tree-shaking for `dist/debug`, but the problems as I see them are:

1. Additional code is needed in both the worker and hooks to allow for rendering wireframes

2. To avoid polluting the production version of the lib, we would need to maintain a second copy of both the worker and hooks

So in my opinion, the main issue is how to maintain the debug version of the lib alongside the production version - minimal duplication of code, etc.

The boundary box helper is awesome! But you don't get as much information with the bounding box alone. Here's a small example that shows how useful the wireframes can be for compound shapes and convex polyhedrons: http://novas-playground.surge.sh/

If you'd like to pair on this sometime, we could screenshare or use VS Live Share - but I believe we are in different time zones? 😸

**Comment by codynova** [comment]
[This](https://schteppe.github.io/cannon.js/demos/shapes.html) is a great example of the sorts of debug data I'd like to expose in `use-cannon`. Check out the options under the `Rendering` panel.

**Comment by drcmda** [comment]
i see, that looks way more useful than just bounds.

as for the hooks, we can make a debug.tsx which fetches the hooks and adds overrides:

```jsx
import { useBox as useBoxOriginal, ... } from './hooks'

export function useBox(args) {
  const ret = useBoxOriginal(args)
  // do stuff
  return ret
}
```

this way we dont need to duplicate code, because that is a sure recipe for trouble.

**Comment by Franckapik** [comment]
Just to understand, before taking too much time on this, for now there isn't a way to debug body shape using use-cannon, right ? 
Thank you by the way for all your work! :)

**Comment by codynova** [comment]
@Franckapik That's correct. The best you can get right now is [bounding boxes](https://github.com/react-spring/use-cannon/issues/21#issuecomment-602282322). As soon as I can find some time I'll work on this some more. The debugging code is finished, we just need to get the data from the worker to the debug code as elegantly as possible.

**Comment by Franckapik** [comment]
@codynova, i have tried to insert or replace the code in hooks.ts in node_module (which i know is not adviced) but i did not see some bounding box so maybe it's too hard for me now to play with the core of use-cannon... :/
I work all days now to understand how i can use physics in my webgl game... I hope i could help next to show how to play with it ! :)

**Comment by codynova** [comment]
@Franckapik Try like this bfe7e1e1

**Comment by Franckapik** [comment]
Thank you for this commit  @codynova . But i am not shure of what i did. I change manually hooks.ts according to the new file, then i npm install and npm run build, but now i have a error in console like suscribe is not a function or R is not a function (from web.js or Provider.js...) :/

**Comment by Franckapik** [comment]
I will try to have a look again on a helper to see bodies on mesh to have a better debugging. 
Just before doing this, is there some news about it ? 
Thank you!!

**Comment by elisherer** [comment]
I created the following PR #190 , can you check it out?

My approach was "monkey patching" the `useBody` hook to collect body information. And then on every frame coming from the worker, update those bodies and use the original cannon debugger.

To create the same body the worker creates (when using `addBodies`) I extracted the logic to a separate file which is referenced both by the client and worker code.
