### ISSUE TITLE
Pause Simulation

### ISSUE THREAD

**Issue by funwithtriangles** [pmndrs/use-cannon#212]
Currently there doesn't seem to be a way to pause/play the simulation. I'm assuming the best approach would be to just have some state that prevents the `loop` from firing inside of the `useFrame` hook?

**Comment by stockHuman** [comment]
This is resolved in #226, with the caveat that it may be insufficient if your setup depends on invalidating and _not_ stepping through physics at the same time.

**Comment by seflless** [comment]
@funwithtriangles It's not clear to me if you can pause/play/step explicitly now. I'm interested in some experiments around replay-able physics visualizations.
