### ISSUE TITLE
useSphere crashes on most recent `use-cannon` and `react-three-fiber`

### ISSUE THREAD

**Issue by calvind777** [pmndrs/use-cannon#216]
Bug Demo: https://codesandbox.io/s/use-cannon-applyforce-bug-report-forked-b5vim

I encountered this in my own project as well, and changing `useSphere` to `useBox` worked perfectly. You can also observe that bumping down the `@react-three/fiber` version to `2.2.0` fixes the crash.

**Comment by bjornstar** [comment]
Interesting, if you remove the debug wrapper it doesn't crash.

**Comment by drcmda** [comment]
should be fixed
