### ISSUE TITLE
Major performance regression in 2.3.4

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [pmndrs/use-cannon#220]
Hi, I encountered a major performance regression with Cannon:

System: Windows 10
Browser: Chrome 91
Graphics Card:  nvidia geforce rtx 2060 super

2.3.4 (bug) - 200 balls performance is very slow
https://codesandbox.io/s/bug-ballpit-234-xwg3y

versus

2.3.3 (control) - 200 balls performance is fine
https://codesandbox.io/s/control-ballpit-233-gfofn

**Comment by drcmda** [comment]
spreading the args fixes it? the patch is on npm

**Comment by TimvanScherpenzeel** [comment]
It works, thanks! 👍
