### ISSUE TITLE
Spheres

### ISSUE THREAD

**Issue by David-Beale** [pmndrs/use-cannon#223]
Hey, just wondering if anyone else has noticed this weird bug with spheres:

https://youtu.be/84mANXBYZ3Q

They seem to be exerting forces on each other from a distance. Works fine with boxes. You can see it with the cube heap example if you change them to spheres.

**Comment by David-Beale** [comment]
slightly better example
https://youtu.be/pV_bhVXl1Kc

**Comment by stockHuman** [comment]
Hello there, would you have this issue in a codesandbox?
