### ISSUE TITLE
Unable to read postiion/rotation after update, this is now more expensive (!?)

### ISSUE THREAD

**Issue by AlexandrosGounis** [pmndrs/use-cannon#238]
Commit cd7427705506fea3bb700e4a748dbee8271e67af changed `matrixAutoUpdate`. Consider a scenario like this:

```ts
const { camera } = useThree()

const [ref, api] = useSphere(() => ({
    mass: 1,
    args: 0.5,
    position: [20, 10, 0],
}))

...

useFrame(() => {
     camera.position.set(ref.current.position[0] - 10, 10, current.position[2]) // ref.current.position not updated anymore
})
```

In order to get the position now, I have to call `ref.current.getWorldPosition()` which appears to be more expensive and because this is inside a frameLoop it might affect performance. 

What is the proper way to handle this? Can I force `ref` to always update the position?

**Comment by idigger** [comment]
Solved?

**Comment by AlexandrosGounis** [comment]
I wouldn't consider this an issue anymore, there is a workaround. For instance, one may subscribe to `api.position` and get the position from there. I tend to use regular `requestAnimationFrame` rather than `useFrame` as I have more control over it.

**Comment by drcmda** [comment]
the objects are driven by matrix (matrixAutoUpdate=false) so pos/rot/scale are stale. this is faster. you can extract the position either from the matrix or use getworldpos, both shouldn't be an overhead. or by subscription ofc.

**Comment by idigger** [comment]
Thank you for your replies.
