### ISSUE TITLE
2.6.0 npm package dist folder missing

### ISSUE THREAD

**Issue by arya-s** [pmndrs/use-cannon#251]
Hello,

it looks like 2.6.0 fails to build on install, there's no `build` folder inside `node_modules/@react-three/cannon`. 

Example sandbox: https://codesandbox.io/s/snowy-wood-uovvp?file=/src/App.tsx

**Comment by stockHuman** [comment]
Thank you, and how strange. Build tooling has not changed as far as I know, so I can't tell why this would be. `2.6.1` released to fix.
