### ISSUE TITLE
R3F object's args aren't respected in useSphere

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/use-cannon#287]
`useSphere` will default to using default sphere construct args, and it seems that we cannot override this by explicitly passing `args` into the hook. Furthermore, this will work if you specify `args: [n]` but only where n >= 1.

Here's a recreation I picked up from the Discord from @andersonleite:
 - https://codesandbox.io/s/3-r3f-physics-forked-91f3d

**Comment by Krispy3000** [comment]
Might be related: https://github.com/pmndrs/use-cannon/issues/235

**Comment by bjornstar** [comment]
It seems this is a major point of confusion. I'll go ahead and change the args for `useSphere` to an array with a single entry.

**Comment by andersonleite** [comment]
Just to confirm, I updated to v4 and it works.
https://codesandbox.io/s/u327l?file=/src/index.js

Thanks @bjornstar
