### ISSUE TITLE
Worker has no handler for setMaterial op

### ISSUE THREAD

**Issue by isaac-mason** [pmndrs/use-cannon#339]
While working on a PR for #327, I noticed that the `material` atomic prop has an API generated for it, but as far as I can see there is no worker handler for a `setMaterial` op.

Here's a quick thrown together example - one cube has its material set on creation in it's body props, another tries to set it in an effect.
https://codesandbox.io/s/missing-setmaterial-op-repro-3bhes?file=/src/index.js

Is this just a miss? I take it this API wouldn't be used often.

I'm happy to create a PR to add the missing handler to the worker if it's something we want to add 🙂

**Comment by bjornstar** [comment]
If it's something you want to use, go for it.

**Comment by isaac-mason** [comment]
Sure, created a quick PR for this now: https://github.com/pmndrs/use-cannon/pull/340
