### ISSUE TITLE
Debug does not work with instancedMesh

### ISSUE THREAD

**Issue by krispya** [pmndrs/use-cannon#364]
The Debug component doesn't outline instancedMesh. 
Here is a Codesandbox with a mix of non-instanced and instanced meshes (inside the Boxes component): https://codesandbox.io/s/use-cannon-sampler-test-gixxzl?file=/src/Boxes.js

Here is a cleaner example: https://codesandbox.io/s/use-cannon-debug-instance-example-s912po

**Comment by bjornstar** [comment]
Fixed by #366
