### ISSUE TITLE
Can't  show in android browser.

### ISSUE THREAD

**Issue by neciszhang** [pmndrs/use-cannon#390]
Hi,
    When I open '[cannon.pmnd.rs](https://cannon.pmnd.rs/)' in android browser, it can't shown in it.And show error;
![image](https://user-images.githubusercontent.com/16221107/173226836-2d0155f7-b1c6-44fc-af15-f0ae6d6d7c5d.png)

**Comment by isaac-mason** [comment]
Thanks! Can you share which browser you are using? I'm able to access cannon.pmnd.rs on Android Chrome, Firefox, and Samsung Internet fine.
