### ISSUE TITLE
Add body existence check in step function

### ISSUE THREAD

**Issue by alex-shortt** [pmndrs/use-cannon#407]
Hello - something about my usage seems to be wrong and I'd love some help figuring that out, but an issue regardless of my setup is the error `Cannot read properties of undefined (reading 'position')` coming from [this line.](https://github.com/pmndrs/use-cannon/blob/ed5ad2a1b6f06c7840d28a5f5ce96ea5fce6c7c3/packages/cannon-worker-api/src/worker/operations/step.ts#L43) For some reason my body subscriptions are losing values but not disappearing from state. There should definitely be a check there . I'll submit a pr in a second.

As for what may be wrong with my setup, I'm using the `Physics` component in a separate component, [seen here](https://github.com/musehq/spacesvr/blob/master/src/layers/Physics/index.tsx), which upon re-render may be losing internal state.

**Comment by alex-shortt** [comment]
Submitted a pr here: #408 

As for the cause, after looking at the source I can better describe it as unloaded bodies don't seem to remove subscriptions. So it's probably not the `Physics` component itself that's resetting since it's still aware of the subscriptions, but that the body is being unloaded without the subscriptions being unloaded.

**Comment by darkopetrovic** [comment]
I've the same error when using api subscription and when objects are removed from the scene. Don't know how but then the api stops working for the other objects too.

**Comment by bjornstar** [comment]
Could you share a reproduction with us then we can be sure to fix it.

**Comment by alex-shortt** [comment]
@bjornstar the problem seems clear, as pointed out in #411, subscriptions aren't being removed when the body is removed. am i missing something?

https://github.com/pmndrs/use-cannon/blob/9259f8700ef96e0555381afd4ec96e54e3bf507b/packages/cannon-worker-api/src/worker/index.ts#L48-L52

**Comment by alex-shortt** [comment]
now fixed in #412

**Comment by mattblackdev** [comment]
I experienced this when I setup a subscription but did not ever call the returned `unsubscribe` function. Don't forget to unsub like `useEffect(() => unsub, [])` so it gets called when your component unmounts.
