### ISSUE TITLE
Is it possible to use cannon-worker-api with vanilla cannon-es?

### ISSUE THREAD

**Issue by imokya** [pmndrs/use-cannon#413]
Is it possible to use cannon-worker-api with vanilla cannon-es, can we have an example of this?

**Comment by isaac-mason** [comment]
Hey @imokya, that's the eventual intent.

Worker logic used to live in the `@react-three/cannon` package, but was moved into a new `cannon-worker-api` package as part of https://github.com/pmndrs/use-cannon/issues/327.

You _can_ use `cannon-worker-api` with vanilla cannon-es now, but it doesn't yet have a nice high-level API, and there's no examples right now.

Unfortunately I haven't had much time to push this along. If it's something you're keen for, and you're able to contribute, contribs are very welcome on this issue - https://github.com/pmndrs/use-cannon/issues/327

I'll close this issue for now, but feel free to add to the above issue.
