### ISSUE TITLE
GET http://127.0.0.1:5173/node_modules/.vite/deps/@react-three_cannon.js?v=78dbe0b1 net::ERR_ABORTED 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by PrakharGupta36** [pmndrs/use-cannon#415]
There is nothing more to say. I'm not being able to use use-cannon at all 

<img width="412" alt="Screenshot 2022-10-12 at 4 41 34 PM" src="https://user-images.githubusercontent.com/72487117/195327995-ca94d14f-f5f9-4a76-97e0-4ab3a3270b60.png">

Can anyone help

**Comment by edunwa302** [comment]
where you to solve this problem

**Comment by bjornstar** [comment]
Please ask for help using the [Discussions](https://github.com/pmndrs/use-cannon/discussions) feature instead of creating an issue, thank you!
