### ISSUE TITLE
Detect collision between two kinematic objects

### ISSUE THREAD

**Issue by berkaycirak** [pmndrs/use-cannon#427]
Hi,
I am trying to do a project where two models in it. There is a kinematic ball which can move with mouse, and also there is another ball which stays as a static. I want to detect when kinematic ball collides with that static ball. Is there any idea? 
https://codesandbox.io/s/ballpit-forked-q87cos?file=/src/App.js

**Comment by berkaycirak** [comment]
I think there is only detection between a dynamic type and a non-dynamic type of objects. Therefore, should I use a static floor just below the dynamic object?

**Comment by berkaycirak** [comment]
I have solved that issue by removing mass and passing isTrigger:true prop for moving ball
`const [ref] = useSphere((index) => ({ type: "Dynamic", isTrigger: true, position: [0, 0, 0], args: [1.2] }))`

**Comment by Pipe-Runner** [comment]
@berkaycirak Thank you, this was a crucial piece that the documentation does not mention.
