### ISSUE TITLE
Circle and Cylinder sinks into Plane

### ISSUE THREAD

**Issue by MorningLit** [pmndrs/use-cannon#432]
### Discussed in https://github.com/pmndrs/use-cannon/discussions/431

<div type='discussions-op-text'>

<sup>Originally posted by **MorningLit** April 28, 2023</sup>
Hi all, not sure if this is normal for this library or it's my code, but I am trying to make a coin-flipping website and I am not sure why the coin is "sunk" or "dug" into the plane.
Example:
![image](https://user-images.githubusercontent.com/57279935/235130189-612804e7-7093-433a-8c9a-93cc64a336c3.png)
![image](https://user-images.githubusercontent.com/57279935/235130755-8bd7cfd4-6a6f-4c61-8ba6-5f334ce04711.png)

I have read this issue but it doesn't seem to address it https://github.com/pmndrs/use-cannon/issues/58
I tried both circleGeometry and cylinderGeometry but both produce the same results. Is this the supposed default behaviour that I am supposed to be seeing?</div>

**Comment by isaac-mason** [comment]
Until it's identified that this is a real bug, it's probably worth keeping this to discussions. Feel free to reach out on discord too.

Will reply on your discussion
